### PR TITLE
Christmas when it is on a weekend

### PR DESCRIPTION
**Pull request by seemaullal**
We don't want to count Monday as a holiday if Christmas is on a Sunday

### CODE REVIEW

**Comment by sleiyer** [comment]
@seemaullal @colinroper Is this change strictly for email copy changes?

Maybe i'm missing something but 12/26/2016 and 1/2/2017 are bank holidays and this will affect our payments logics as well.

**Comment by seemaullal** [comment]
nope this is only for showing Olark chat. We use "Gusto" holidays to determine when to show Olark chat since our office holidays don't follow the federal bank holidays exactly. The "US" holidays we use elsewhere in the app are unaffected

**Comment by seemaullal** [comment]
@sleiyer Check out https://github.com/Gusto/zenpayroll/blob/684f4688a4c22bca6859b1cc22937b84c02b6184/lib/date_extensions.rb#L81 vs Line 83. This change only affects line 83 which would then affect https://github.com/Gusto/zenpayroll/blob/684f4688a4c22bca6859b1cc22937b84c02b6184/app/services/care/support_hour.rb and https://github.com/Gusto/zenpayroll/blob/684f4688a4c22bca6859b1cc22937b84c02b6184/app/services/care/support_hour.rb

**Comment by colinroper** [comment]
@sleiyer I only need it for the Olark chat widget

**Comment by sleiyer** [comment]
@seemaullal Ah gotcha didn't know we split it into a gusto observed calendar. What is the default behavior when calling `Date.today.holiday?` without any arg. Does it default to us observed?

**Comment by seemaullal** [comment]
@sleiyer No, the gem is somewhat dumb and looks at every holiday in every country sadly. That's a good question though– found 2 places where we use that so I'll make a separate PR in ZP to fix those.

Example–
```ruby
[61] pry(main)> Date.new(2016,7,1).holiday?
=> true
[62] pry(main)> Date.new(2016,7,1).holiday?(:us)
=> false
# July 1 is Canada Day
```

**Comment by sleiyer** [comment]
Ah yah so there might be some existing bug with those logic. Looks like:
```
/Users/sheng.lei/workspace/zenpayroll/app/services/maintenance/jobs/system/form_processor.rb:
    9  
   10            today = Date.today
   11:           if today.weekend? || today.holiday?
   12              log 'Today is a weekend of holiday - not faxing any forms'
   13            else

/Users/sheng.lei/workspace/zenpayroll/app/services/payments/jobs/maintenances/historical_chase_onboarder.rb:
    7  
    8        def perform(limit=300, period=default_period)
    9:         return if Date.today.holiday?
   10          return if FeatureFlag.active? DISABLE_MIGRATIONS
   11  

/Users/sheng.lei/workspace/zenpayroll/app/services/payments/jobs/maintenances/payer_origination_bank_migrator.rb:
    7  
    8        def perform(last_updated_on=default_period)
    9:         return if Date.today.holiday?
   10          return if FeatureFlag.active? DISABLE_MIGRATIONS
```
I think the form processor should be okay, since we'll fax the day after. But for other 2, Do you mind cc/assigning that PR to someone on payments team to make sure we are okay

**Comment by zp-alfred** [comment]
Accepted by sleiyer!

**Pull request closed without merging**
